name: chat_app_project
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_colorpicker: ^1.0.3
  qr_flutter: ^4.1.0
  iconsax: ^0.0.8
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  uuid: ^4.5.1
  intl: ^0.19.0
  gap: ^3.0.1
  image_picker: ^1.1.2
  firebase_storage: ^12.3.3
  cached_network_image: ^3.4.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  firebase_messaging: ^15.1.3
  http: ^1.2.2
  photo_view: ^0.15.0
  modal_progress_hud_nsn: ^0.5.1
#  qr_code_scanner: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/te2.png


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

